### ISSUE TITLE
Error while reshaping tensor in `split_last_dimension` of `common_attention.py`

### ISSUE THREAD

**Issue by chatrasen** [ZhenYangIACAS/unsupervised-NMT#4]
The code is successfully able to load the embeddings and after that, it throws this error.
@ZhenYangIACAS The Traceback is as follows:

```
Traceback (most recent call last):
  File "train_unsupervised.py", line 248, in <module>
    train(config)
  File "train_unsupervised.py", line 190, in train
    feed_dict={model.src_a_pl: batch_shuffle[0], model.dst_a_pl: batch[0]})
  File "/home/du4/14CS30007/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/du4/14CS30007/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/du4/14CS30007/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/du4/14CS30007/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 1956000 values, but the requested shape requires a multiple of 52160
	 [[Node: dec_shared_block/block_0/decoder_self_attention/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](dec_shared_block/block_0/decoder_self_attention/split, dec_shared_block/block_0/decoder_self_attention/concat)]]
	 [[Node: gradients/dec_aindep_block/block_0/conv_hidden_relu/Squeeze_grad/Shape/_235 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3529_...grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'dec_shared_block/block_0/decoder_self_attention/Reshape', defined at:
  File "train_unsupervised.py", line 248, in <module>
    train(config)
  File "train_unsupervised.py", line 27, in train
    model.build_variational_train_model()
  File "/home/du4/14CS30007/MTP_2/extras/unsupervised-NMT/model.py", line 170, in build_variational_train_model
    step='f')
  File "/home/du4/14CS30007/MTP_2/extras/unsupervised-NMT/model.py", line 621, in variational_decoder
    self_attention_bias, layers_share, "dec_shared_block", reuse=reuse if step=='f' else True)
  File "/home/du4/14CS30007/MTP_2/extras/unsupervised-NMT/model.py", line 765, in build_dec_block
    summaries=self._summary),
  File "/home/du4/14CS30007/MTP_2/extras/unsupervised-NMT/tensor2tensor/common_attention.py", line 404, in multihead_attention
    q = split_heads(q, num_heads)
  File "/home/du4/14CS30007/MTP_2/extras/unsupervised-NMT/tensor2tensor/common_attention.py", line 267, in split_heads
    return tf.transpose(split_last_dimension(x, num_heads), [0, 2, 1, 3])
  File "/home/du4/14CS30007/MTP_2/extras/unsupervised-NMT/tensor2tensor/common_attention.py", line 235, in split_last_dimension
    ret = tf.reshape(x, tf.concat([tf.shape(x)[:-1], [n, -1]], 0))
  File "/home/du4/14CS30007/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6113, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/du4/14CS30007/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/du4/14CS30007/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/du4/14CS30007/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 1956000 values, but the requested shape requires a multiple of 52160
	 [[Node: dec_shared_block/block_0/decoder_self_attention/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](dec_shared_block/block_0/decoder_self_attention/split, dec_shared_block/block_0/decoder_self_attention/concat)]]
	 [[Node: gradients/dec_aindep_block/block_0/conv_hidden_relu/Squeeze_grad/Shape/_235 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3529_...grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```

**Comment by chatrasen** [comment]
There was an error in the dimension of the embeddings, it should be 512
